<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE addressbook [
  <!ELEMENT person (firstname*, lastname, (address, mail:address)?)>
  <!ELEMENT lastname (#PCDATA)>
  <!ELEMENT firstname (#PCDATA)>
  <!ELEMENT addressbook (person*, institution*)>
  <!ATTLIST addressbook xmlns CDATA #FIXED "http://www.anderes.org/namespaces/addressbook"
   					    xmlns:mail CDATA #FIXED "http://www.anderes.org/namespaces/mail">
  
  <!ATTLIST person id ID #REQUIRED institutions IDREFS #IMPLIED>
  <!ELEMENT institution (bezeichnung, (address*, mail:address*)?)>
  <!ELEMENT bezeichnung (#PCDATA)>
  <!ATTLIST institution id ID #REQUIRED>
  <!ELEMENT address (street?, pobox?, city?)>
  <!ATTLIST address type (real|postal) "real">
  <!ELEMENT street (#PCDATA)>
  <!ELEMENT city (#PCDATA)>
  <!ELEMENT mail:address (#PCDATA)>
]>

<addressbook xmlns="http://www.anderes.org/namespaces/addressbook"
	xmlns:mail="http://www.anderes.org/namespaces/mail">
	
	<person id="p4711" institutions="i2391">
		<firstname>Hans</firstname>
		<lastname>Müller</lastname>
		<address type="real">
			<street>Bahnhofplatz 1</street>
			<city>München</city>
		</address>
		<mail:address>h.mueller247@web.de</mail:address>
	</person>
	
	<person id="p4712">
		<firstname>Fritz</firstname>
		<lastname>Meier</lastname>
	</person>
	<institution id="i2391">
		<bezeichnung>Fachhochschule Augsburg</bezeichnung>
	</institution>
</addressbook>