=== eismeraldo/edu/xml/src/main/resources/org/anderes/edu/xml/Systeminformationen.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="systeminformationen">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Betriebssystem" type="xs:string"/>
				<xs:element name="Version" type="xs:string"/>
				<xs:element name="Prozessor" type="xs:string"/>
				<xs:sequence>
					<xs:element ref="Komponenten"/>
					<xs:element ref="Hardwareresourcen"/>
				</xs:sequence>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Komponenten">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Speicher">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Laufwerke">
								<xs:complexType>
									<xs:sequence>
										<xs:element ref="Laufwerk" maxOccurs="unbounded"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="storages">
								<xs:complexType>
									<xs:sequence>
										<xs:element ref="Datenträger" maxOccurs="unbounded"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="CD">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="Beschreibung"/>
						</xs:sequence>
						<xs:attribute name="Laufwerksbuchstabe" type="Laufwerksbuchstabe"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Hardwareresourcen">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="DMA">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Resource" type="xs:string"/>
							<xs:element name="Gerät" type="xs:string"/>
							<xs:element ref="Status"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Datenträger">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Beschreibung"/>
				<xs:element name="Hersteller" type="xs:string"/>
				<xs:element name="Modell" type="xs:string"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Status">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="OK"/>
				<xs:enumeration value="ERROR"/>
				<xs:enumeration value="UNKNOWN"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Beschreibung">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="500"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Laufwerk">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Beschreibung"/>
				<xs:element name="Dateisystem" type="xs:string" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="Laufwerksbuchstabe" type="Laufwerksbuchstabe"/>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="Laufwerksbuchstabe">
		<xs:restriction base="xs:string">
			<xs:pattern value="[A-Z]:"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== eismeraldo/edu/xml/src/main/resources/org/anderes/edu/xml/systeminformationen.xml
<?xml version="1.0" encoding="UTF-8"?>
<systeminformationen xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Systeminformationen.xsd">
	<Betriebssystem>Microsoft Windows 7 Professional</Betriebssystem>
	<Version>6.1.7601 Service Pack 1 Build 7601</Version>
	<Prozessor>Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz, 3401 MHz, 4 Kern(e), 8 logische(r) Prozessor(en)</Prozessor>
	<Komponenten>
		<Speicher>
			<Laufwerke>
				<Laufwerk Laufwerksbuchstabe="C:">
					<Beschreibung>Lokale Festplatte</Beschreibung>
					<Dateisystem>NTFS</Dateisystem>
				</Laufwerk>
				<Laufwerk Laufwerksbuchstabe="E:">
					<Beschreibung>CD</Beschreibung>
				</Laufwerk>
			</Laufwerke>
			<storages>
				<Datentr채ger>
					<Beschreibung>Laufwerk</Beschreibung>
					<Hersteller>Standardlaufwerk</Hersteller>
					<Modell>INTEL SSDSA2CW160G3</Modell>
				</Datentr채ger>
			</storages>
		</Speicher>
		<CD Laufwerksbuchstabe="E:">
			<Beschreibung>CD-ROM-Laufwerk</Beschreibung>
		</CD>
	</Komponenten>
	<Hardwareresourcen>
		<DMA>
			<Resource>Kanal 4</Resource>
			<Ger채t>DMA-Controller</Ger채t>
			<Status>OK</Status>
		</DMA>
	</Hardwareresourcen>
</systeminformationen>
