=== eismeraldo/edu/xml/src/main/resources/org/anderes/edu/xml/cookbook/cookbook.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="cookbook">
		<!-- Definition des Kochbuchs -->
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="recipe" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="recipe">
		<!-- Definition eines Rezepts -->
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="title"/>
				<xs:element name="preample" type="description" minOccurs="0"/>
				<xs:element ref="image" minOccurs="0"/>
				<xs:element ref="noOfPerson"/>
				<xs:element ref="ingredients"/>
				<xs:element name="preparation" type="description"/>
				<xs:element ref="modification"/>
			</xs:sequence>
			<xs:attribute name="id" type="xs:positiveInteger" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="ingredients">
		<!-- Definition der Zutatenliste -->
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ingredient" minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ingredient">
		<!-- Definition einer Zutat -->
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="quantity"/>
				<xs:element name="description" type="description"/>
				<xs:element ref="comment" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="quantity">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="15"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="title">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="5"/>
				<xs:maxLength value="150"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="noOfPerson">
		<xs:simpleType>
			<xs:restriction base="xs:positiveInteger">
				<xs:enumeration value="2"/>
				<xs:enumeration value="4"/>
				<xs:enumeration value="6"/>
				<xs:enumeration value="8"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="modification">
		<xs:simpleType>
			<xs:restriction base="xs:date"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="image">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="url"/>
				<xs:element name="description" type="description"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="url">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:pattern value="\w+[.](jpeg|jpg|png)+"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="comment">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="50"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:simpleType name="description">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="1000"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== eismeraldo/edu/xml/src/main/resources/org/anderes/edu/xml/cookbook/cookbook.xml
<?xml version="1.0" encoding="UTF-8"?>
<cookbook xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///H:/Wissen/cookbook.xsd">
	<recipe id="1">
		<title>BÃ¼nder Nusstorte</title>
		<preample>Einleitung</preample>
		<image>
			<url>nusstorte.jpg</url>
			<description>Nusstorte</description>
		</image>
		<noOfPerson>2</noOfPerson>
		<ingredients>
			<ingredient>
				<quantity>200g</quantity>
				<description>Mehl</description>
			</ingredient>
			<ingredient>
				<quantity>2dl</quantity>
				<description>Rahm</description>
				<comment>Vollrahm/Halbrahm</comment>
			</ingredient>
		</ingredients>
		<preparation>So gehts ....</preparation>
		<modification>2011-12-29</modification>
	</recipe>
	<recipe id="2">
		<title>Pizza</title>
		<preample>Einleitung</preample>
		<image>
			<url>pizza.jpg</url>
			<description>Pizza</description>
		</image>
		<noOfPerson>2</noOfPerson>
		<ingredients>
			<ingredient>
				<quantity>250g</quantity>
				<description>Mehl</description>
			</ingredient>
			<ingredient>
				<quantity>1.5dl</quantity>
				<description>Wasser</description>
				<comment>lauwarm</comment>
			</ingredient>
		</ingredients>
		<preparation>So gehts ....</preparation>
		<modification>2011-02-22</modification>
	</recipe>
</cookbook>
